var selectedRow =null; 
function onFormSubmit(e){
event.preventDefault();
var formData = readFormData();
if(selectedRow == null){
    insertNewRecord(formData);
}
else
{
    updateRecord(formData);
}
resetForm();
}


// retrive the data
function readFormData(){
    var formData= {};
    formData["productCode"]= document.getElementById("productCode").value;
    formData["product"]= document.getElementById("product").value;
    formData["Qyt"]= document.getElementById("Qyt").value;
    formData["perPrice"]= document.getElementById("perPrice").value;
    return formData;
}

// insert the data
function insertNewRecord (data){
    var table =document.getElementById("storeList").getElementsByTagName('tbody')[0];
    var newRow=table.insertRow(table.length);
 cell1 =newRow.insertCell(0);
    cell1.innerHTML= data.productCode;
 cell2 =newRow.insertCell(1);
    cell2.innerHTML= data.product;
 cell3 =newRow.insertCell(2);
    cell3.innerHTML= data.Qyt;
 cell4 =newRow.insertCell(3);
    cell4.innerHTML= data.perPrice;
 cell5 =newRow.insertCell(4);
    cell5.innerHTML= '<button onClick="onEdit(this)">Edit</button> <button onClick="onDelete(this)">Delete</button>'
}

// Edit the data
function onEdit(td){
    selectedRow = td.parentElement.parentElement;
    document.getElementById("productCode").value =selectedRow.cells[0].innerHTML;
    document.getElementById("product").value =selectedRow.cells[1].innerHTML;
    document.getElementById("Qyt").value =selectedRow.cells[2].innerHTML;
    document.getElementById("perPrice").value =selectedRow.cells[3].innerHTML;
}

function updateRecord(formData){
    selectedRow.cells[0].innerHTML = formData.productCode;
    selectedRow.cells[1].innerHTML = formData.product;
    selectedRow.cells[2].innerHTML = formData.Qyt;
    selectedRow.cells[3].innerHTML = formData.perPrice;
}

// delete the data
function onDelete(td){
    if (confirm('Do You Want to Delete This record?')){
        row=td.parentElement.parentElement;
        document.getElementById('storeList').deleteRow(row.rowIndex);
        resetForm();
    }
}

// reset the data
function resetForm(){
    document.getElementById("productCode").value ='';
    document.getElementById("product").value ='';
    document.getElementById("Qyt").value ='';
    document.getElementById("perPrice").value ='';
    selectedRow=null;
}